# Generated by Django 4.1.3 on 2023-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBJusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
