# Generated by Django 4.1.3 on 2023-02-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBJusers', '0002_event_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(default='', null=True),
        ),
    ]
