# Generated by Django 4.1.3 on 2023-02-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OBJusers', '0005_alter_profile_followsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followsEvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OBJusers.event'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
