# Generated by Django 4.1.7 on 2023-03-31 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OBJusers', '0008_event_user_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='game_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
